import type { DayNight } from '../../types'

/** v10 night materials; W4 can extend the daylight surface colours here. */
const night: Record<string, string> = {
  'ink': '#0e121c',
  'black': '#000',
  'paper': '#fff',
  'metal': '#6b7488',
  'light': '#d9fbff',
  'muted': '#9aa3b8',
  'cyan': '#34d7ff',
  'blue': '#3b7bd6',
  'project': 'var(--wf-project, var(--info))',
  'amber': '#ffb020',
  'red': '#ff4d5a',
  'warm': '#ffe9b0',
  'ice': '#f2f4f8',
  'deep': '#0a0d16',
  'horizon': '#3a4152',
  'ocean': '#173a6e',
  'floor': '#20252f',
  'glass': '#0b0f18',
  'scene-light': 'var(--launch-light)',
  'scene-ink': 'var(--launch-ink)',
  'gBlue-stop-0': 'color-mix(in srgb, var(--launch-project) 60%, var(--launch-paper))',
  'gBlue-stop-1': 'var(--launch-project)',
  'gBlue-stop-2': 'color-mix(in srgb, var(--launch-project) 60%, var(--launch-ink))',
  'gBlueL-stop-0': 'color-mix(in srgb, var(--launch-project) 35%, var(--launch-paper))',
  'gBlueL-stop-1': 'var(--launch-project)',
  'gBlueL-stop-2': 'color-mix(in srgb, var(--launch-project) 78%, var(--launch-ink))',
  'gBlueD-stop-0': 'var(--launch-project)',
  'gBlueD-stop-1': 'color-mix(in srgb, var(--launch-project) 45%, var(--launch-ink))',
  'gGrey-stop-0': '#6b7488',
  'gGrey-stop-1': '#3a4152',
  'gGrey-stop-2': '#20252f',
  'gGreyD-stop-0': '#3f4658',
  'gGreyD-stop-1': '#171b24',
  'gDark-stop-0': '#2b303d',
  'gDark-stop-1': '#0f1219',
  'gGold-stop-0': '#fbe6a3',
  'gGold-stop-1': '#e2b54c',
  'gGold-stop-2': '#9c6f1e',
  'gRed-stop-0': '#ff8a8a',
  'gRed-stop-1': '#a51f1f',
  'gVisor-stop-0': '#d9fbff',
  'gVisor-stop-1': '#2cb8ff',
  'gFlame-stop-0': '#ffffff',
  'gFlame-stop-1': '#8fe9ff',
  'gFlame-stop-2': '#2a7bff',
  'gWall-stop-0': '#101521',
  'gWall-stop-1': '#1b2232',
  'gFloor-stop-0': '#1c2334',
  'gFloor-stop-1': '#0b0e16',
  'gCone-stop-0': '#ffe9b0',
  'gRgb-stop-0': '#4ad9c4',
  'gRgb-stop-1': '#4a9eff',
  'gRgb-stop-2': '#8b7bf7',
  'gRgb-stop-3': '#c96bd8',
}
const day: Record<string, string> = { deep: '#94b8d6', ocean: '#548eb1', horizon: '#dae1d7' }

export function applyPalette(root: SVGGElement, value: DayNight) {
  const colors = value === 'day' ? { ...night, ...day } : night
  for (const [key, color] of Object.entries(colors)) root.style.setProperty('--launch-' + key, color)
  root.style.setProperty('--launch-lamp-opacity', value === 'day' ? '.24' : '1')
}
